# Generated by Django 6.0.5 on 2026-06-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_deal_associated_lead'),
        ('leads', '0002_lead_city_lead_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealactivity',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='associated_lead',
            field=models.ForeignKey(blank=True, db_column='associated_lead_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='leads.lead'),
        ),
    ]
