# Generated by Django 6.0.5 on 2026-05-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_owner', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('New', 'New'), ('In Progress', 'In Progress'), ('Qualified', 'Qualified'), ('Converted', 'Converted'), ('Unqualified', 'Unqualified'), ('Attempted to Contact', 'Attempted to Contact'), ('Contacted', 'Contacted'), ('Closed', 'Closed')], default='New', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
