# Generated by Django 6.0.5 on 2026-05-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('deal', 'Deal'), ('ticket', 'Ticket'), ('company', 'Company'), ('reminder', 'Reminder')], default='system', max_length=50),
        ),
    ]
