# Generated by Django 6.0.5 on 2026-05-19 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('Legal Services', 'Legal Services'), ('Healthcare', 'Healthcare'), ('Real Estate', 'Real Estate'), ('Financial Advisory', 'Financial Advisory'), ('Retail & E-commerce', 'Retail & E-commerce'), ('Logistics & Supply Chain', 'Logistics & Supply Chain'), ('Marketing Agencies', 'Marketing Agencies'), ('Education Technology', 'Education Technology'), ('Technology', 'Technology'), ('Finance', 'Finance'), ('Manufacturing', 'Manufacturing'), ('Other', 'Other')], max_length=100)),
                ('type', models.CharField(choices=[('Prospect', 'Prospect'), ('Customer', 'Customer'), ('Partner', 'Partner'), ('Vendor', 'Vendor'), ('Other', 'Other')], max_length=50)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_employees', models.CharField(blank=True, max_length=50, null=True)),
                ('annual_revenue', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_owner', models.ManyToManyField(blank=True, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
