# Generated by Django 6.0.5 on 2026-05-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_email_meeting_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_status',
            field=models.CharField(default='initiated', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='call',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call',
            name='twilio_sid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
