# Generated by Django 6.0.3 on 2026-05-12 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('industry_type', models.CharField(blank=True, max_length=100)),
                ('country_or_region', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Sales Manager', 'Sales Manager'), ('Sales Representative', 'Sales Representative'), ('Support Agent', 'Support Agent'), ('Marketing Manager', 'Marketing Manager'), ('Viewer', 'Viewer')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
