# Generated by Django 6.0.5 on 2026-06-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Sales Manager', 'Sales Manager'), ('Sales Representative', 'Sales Representative'), ('Support Agent', 'Support Agent'), ('Marketing Manager', 'Marketing Manager'), ('Viewer', 'Viewer')], max_length=50),
        ),
    ]
