# Generated by Django 6.0.5 on 2026-05-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Waiting on us', 'Waiting on us'), ('Waiting on customer', 'Waiting on customer'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='New', max_length=50),
        ),
    ]
