# Generated by Django 6.0.5 on 2026-05-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('Chat', 'Chat'), ('Email', 'Email'), ('Phone', 'Phone'), ('Meeting', 'Meeting')], default='Chat', max_length=50),
        ),
    ]
