# Generated by Django 6.0.5 on 2026-06-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_city_lead_company'),
        ('tickets', '0003_alter_ticket_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='leads.lead'),
        ),
    ]
